### ISSUE TITLE
FFXIV install package download?

### ISSUE THREAD

**Issue by ffxisf** [jpd002/SeventhUmbral#1]
Can you give me FFXIV client download link?
new client version does not work.
FINAL FANTASY XIV - A Realm Reborn

**Comment by jpd002** [comment]
Sorry, I can't provide you with a link to the client for FFXIV 1.0 for legal reasons.

**Comment by DerekTurtleRoe** [comment]
A Realm Reborn is not the same thing. It is the same game essentially, but you need to buy the original disc copy of FFXIV for this emulator to work.

You can buy it here:

http://amzn.to/1FNY7Za

Or you can search elsewhere on the site here:

http://amzn.to/1yhI81w

I'm not sure of Jean will be supporting A Realm Reborn and Lodestone in the future, but my guess is maybe not? It would be a lot of work to support all 3.
