### ISSUE TITLE
Visual Studio 2013 Build Errors

### ISSUE THREAD

**Issue by Caladius** [jpd002/SeventhUmbral#4]
Hey jpd002,
 Unsure if you are even still working on this server, but I am following your instructions to install the server and am encountering a number of build errors when i attempt to do so in Visual Studio 2013.

Is there something that i need to do prior to building the solution that could have been missed? All projects load without issue when opening the solution, but attempting to build is where the issues arise.

**Comment by jpd002** [comment]
What's the error you're getting?

**Comment by Caladius** [comment]
Theres a lot of them. heres a few off the error log. for some reason GitHub wont let me upload an xlsx file.

Error   1   error C2061: syntax error : identifier 'int64'  c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   20  1   Framework
Error   2   error C2146: syntax error : missing ';' before identifier 'Tell'    c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   21  1   Framework
Error   3   error C2433: 'Framework::CStream::uint64' : 'virtual' not permitted on data declarations    c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   21  1   Framework
Error   4   error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   21  1   Framework
Warning 5   warning C4183: 'Tell': missing return type; assumed to be a member function returning 'int' c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   21  1   Framework
Error   6   error C2146: syntax error : missing ';' before identifier 'Read'    c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   22  1   Framework
Error   7   error C2433: 'Framework::CStream::uint64' : 'virtual' not permitted on data declarations    c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   22  1   Framework
Error   8   error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   22  1   Framework
Error   9   error C2061: syntax error : identifier 'uint64' c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   22  1   Framework
Warning 10  warning C4183: 'Read': missing return type; assumed to be a member function returning 'int' c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   22  1   Framework
Error   11  error C2146: syntax error : missing ';' before identifier 'Write'   c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   23  1   Framework
Error   12  error C2433: 'Framework::CStream::uint64' : 'virtual' not permitted on data declarations    c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   23  1   Framework
Error   13  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   23  1   Framework
Error   14  error C2061: syntax error : identifier 'uint64' c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   23  1   Framework
Warning 15  warning C4183: 'Write': missing return type; assumed to be a member function returning 'int'    c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   23  1   Framework
Error   16  error C2146: syntax error : missing ';' before identifier 'GetLength'   c:\users\chris\downloads\server\seventh umbral\framework\include\stream.h   26  1   Framework

**Comment by jpd002** [comment]
I've made some changes to the projects to make it a bit simpler to setup the build environment. All you should need is to make sure your projects are organized in that manner:

C:\Projects
- Dependencies
- Framework
- Palleon
- SeventhUmbral

You will also need some external libraries to get everything to compile:
- MySQL connector (https://dev.mysql.com/downloads/connector/c/)
- TDEmu (http://www.korosoft.net/projects/tdemu/)

I've tried compiling myself and everything should work using the HEAD of each repository. From the errors you're getting, seems like `Types.h` isn't included properly. `uint64` and `int64` are defined in there. Don't hesitate to ask if you've got more questions.

**Comment by Caladius** [comment]
Thanks for the help. 
I will give this a shot when I have a moment. I think i may be missing TDEmu, thanks again, I will let you know how i fare.

**Comment by Caladius** [comment]
If at all possible could we set up a webex session at some point to just have you take a look at my current set up to see if it is something minor that is causing my headaches? 

I have the MySQL connector installed and i believe to have TDEmu as well. 

I made sure Types.h was set to include. Build errors still occur, possibly if you can see it personally you may just be able to slap me in the face and see what i did wrong.

Let me know, thanks!

**Comment by AlexandreCA** [comment]
Hi @Caladius , have you managed to create the server? Can you tell me they are the steps to do to build because we can not say that explicitly tutorial is written on the site. Thank you to you for your future response .

**Comment by jpd002** [comment]
@AlexandreCA If you give me information about the build errors you're getting, I can guide you to potential solutions.

@Caladius Sorry, I'm quite busy, I'm not really available for a web conference session. Are you getting the same build errors?

**Comment by AlexandreCA** [comment]
@jpd002 If I understand well because it is not long since I discovered your site. I have Visual Studio compiles with all the tools you offer ? I use Visual Studio 2015 for another project. A problem with this version ?

EDIT: First error: C:\Play--Framework\build_win32\FrameworkMySql.vcxproj : error
          2nd error:  zlib-1.2.8.vcxproj?

what solution I can find to fill this dependence ?

**Comment by jpd002** [comment]
@AlexandreCA Your directory names don't seem to match what I've described in my post above. Except for the "Projects" folder, every folder needs to be named the same way (ie.: "Dependencies", "Framework", "Palleon" and "SeventhUmbral"). This is needed because the path names inside the projects refer to those names.

**Comment by AlexandreCA** [comment]
Ok! I 'm as in the example above but the problem remains the same . Here is a copy of the error
C:\Projects\Framework\build_win32\FrameworkMySql.vcxproj

**Comment by AlexandreCA** [comment]
@jpd002 Ok! I 'm as in the example above but the problem remains the same . I found her : https://github.com/jpd002/Play-Dependencies

But despite this, its not solves my problem . Here is a copy of the error

C:\Projects\Framework\build_win32\FrameworkMySql.vcxproj : error : Unable to read the project file "FrameworkMySql.vcxproj".
C:\Projects\Framework\build_win32\GeneralSettingsMySql.props(5,5): The imported project "C:\Projects\Framework\build_win32\ExternalDependenciesMySql.userprops" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk.

Just Palleon is OK!

As long as I do not understand how to meet its dependencies , I can not compile the server.

**Comment by jpd002** [comment]
Oh yeah, I forgot about a few steps:

The `Framework\build_win32\ExternalDependenciesMySql.userprops.template` file has to be copied and renamed to `ExternalDependenciesMySql.userprops`. 

Then edit the `ExternalDependenciesMySql.userprops` file and set the value of the `MYSQL_PATH` variable (initially set to `path_to\mysqlclient-5.6`) to the path of your MySQL Connector installation path (ex.: on my side it's set to `D:\Components\mysql-connector-c-6.1.1-win32`).

**Comment by AlexandreCA** [comment]
@jpd002 Ok its works but not 100% . It gives me an error for ExternalDependenciesOpenAl.userprops.template file I renamed ExternalDependenciesOpenAl.userprops . The VS is able to read it but it gives me an error

Error C1083 Unable to open include file : ' al.h ' : No such file or directory FrameworkOpenAl c: \ projects \ framework \ include \ openal \ openaldef.h 5

EDIT: Ok, I found. It had to OpenAL SDK for missing libraries.
https://www.openal.org/downloads/

EDIT2: 
Once I wish compile SeventhUmbral , an error appears at this very precise place . c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible to open the file include : 'mysql.h' : No such file or directory

One idea?

**Comment by jpd002** [comment]
The OpenAL error can be ignored since it's not used by the SeventhUmbral solution.

For the `mysql.h` error, there's also an `ExternalDependencies.userprops` file in the `SeventhUmbral\build_win32` that needs to be modified to refer to the path where you installed the MySQL connector.

**Comment by AlexandreCA** [comment]
@jpd002 I had already discovered her but the problem remains the same 

mysql.h may be in the path C : \ Program Files \ MySQL \ MySQL Connector C 6.1 

![erreur](https://cloud.githubusercontent.com/assets/15184122/12046685/744563c6-ae8b-11e5-8620-44b88c2d8e3b.png)

But the error still occurs .

1>------ Début de la génération : Projet : Daemon, Configuration : Debug Win32 ------
1>  PlayerActor.cpp
1>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
1>  LobbyServerPlayer.cpp
1>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
1>  LobbyServer.cpp
1>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
1>  GameServerPlayer.cpp
1>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
1>  DatabaseConnectionManager.cpp
1>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
1>  Character.cpp
1>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
1>  Génération de code en cours...
========== Génération : 0 a réussi, 1 a échoué, 13 mis à jour, 0 a été ignoré ==========

**Comment by jpd002** [comment]
Humm, you could try quoting your path since there are spaces in it. Not sure MSBuild is smart enough to deal with this automatically.

**Comment by AlexandreCA** [comment]
@jpd002 Spaces relatives to MySQL Connector C 6.1? 
Maybe that like her , it is better? C:\ProgramFiles\MySQL\MySQLConnectorC6.1

EDIT: Nop, nothing change..

1>------ Début de la génération : Projet : DataObjects, Configuration : Debug Win32 ------
2>------ Début de la génération : Projet : RenderObjects, Configuration : Debug Win32 ------
3>------ Début de la génération : Projet : WorldEditor, Configuration : Debug Win32 ------
4>------ Début de la génération : Projet : ActorViewer, Configuration : Debug Win32 ------
4>  ActorViewer.vcxproj -> C:\Projects\SeventhUmbral\build_win32\Win32\Debug\ActorViewer.exe
3>  WorldEditor.vcxproj -> C:\Projects\SeventhUmbral\build_win32\Win32\Debug\WorldEditor.exe
3>  C:\Projects\SeventhUmbral\build_win32..\worldeditor\data\AppConfig.xml
3>  C:\Projects\SeventhUmbral\build_win32..\worldeditor\data\global\font.fnt
3>  C:\Projects\SeventhUmbral\build_win32..\worldeditor\data\global\font_0.png
3>  C:\Projects\SeventhUmbral\build_win32..\worldeditor\data\global\main_scene.xml
3>  C:\Projects\SeventhUmbral\build_win32..\worldeditor\data\global\package.xml
3>  C:\Projects\SeventhUmbral\build_win32..\worldeditor\data\global\skybox.dds
3>  6 fichier(s) copi�(s)
5>------ Début de la génération : Projet : Launcher, Configuration : Debug Win32 ------
4>  C:\Projects\SeventhUmbral\build_win32..\actorviewer\data\AppConfig.xml
4>  C:\Projects\SeventhUmbral\build_win32..\actorviewer\data\global\backward.png
4>  C:\Projects\SeventhUmbral\build_win32..\actorviewer\data\global\font.fnt
4>  C:\Projects\SeventhUmbral\build_win32..\actorviewer\data\global\font_0.png
4>  C:\Projects\SeventhUmbral\build_win32..\actorviewer\data\global\forward.png
4>  C:\Projects\SeventhUmbral\build_win32..\actorviewer\data\global\main_scene.xml
4>  C:\Projects\SeventhUmbral\build_win32..\actorviewer\data\global\package.xml
4>  C:\Projects\SeventhUmbral\build_win32..\actorviewer\data\global\skybox.dds
4>  8 fichier(s) copi�(s)
6>------ Début de la génération : Projet : Daemon, Configuration : Debug Win32 ------
5>  Launcher.vcxproj -> C:\Projects\SeventhUmbral\build_win32\Win32\Debug\Launcher.exe
5>          1 fichier(s) copié(s).
5>          1 fichier(s) copié(s).
7>------ Début de la génération : Projet : Workshop, Configuration : Debug Win32 ------
7>  Workshop.vcxproj -> C:\Projects\SeventhUmbral\build_win32\Win32\Debug\Workshop.exe
7>          1 fichier(s) copié(s).
6>  BLOWFISH.C
6>  ZoneDatabase.cpp
6>  SocketUtils.cpp
6>c:\projects\seventhumbral\daemon\socketutils.cpp(12): warning C4996: 'WSAAddressToStringA': Use WSAAddressToStringW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
6>  c:\program files\windows kits\8.1\include\um\winsock2.h(3556): note: voir la déclaration de 'WSAAddressToStringA'
6>  PacketUtils.cpp
6>  UnknownInventoryPacket.cpp
6>  SetWeatherPacket.cpp
6>  SetTempInventoryPacket.cpp
6>  SetMusicPacket.cpp
6>  SetMapPacket.cpp
6>  SetInventoryPacket.cpp
6>  SetInitialPositionPacket.cpp
6>  SetActorStatePacket.cpp
6>  SetActorPropertyPacket.cpp
6>c:\projects\seventhumbral\daemon\packets\setactorpropertypacket.cpp(46): warning C4267: 'argument' : conversion de 'size_t' en 'uint8', perte possible de données
6>c:\projects\seventhumbral\daemon\packets\setactorpropertypacket.cpp(55): warning C4244: '=' : conversion de 'uint64' en 'unsigned char', perte possible de données
6>  SetActorAppearancePacket.cpp
6>  KeepAlivePacket.cpp
6>  FinishScriptPacket.cpp
6>  DisplayMessagePacket.cpp
6>  CompositePacket.cpp
6>  CommandRequestReplyPacket.cpp
6>  ChangeEquipmentSlotPacket.cpp
6>  BattleActionPacket.cpp
6>  Génération de code en cours...
6>  Compilation en cours...
6>  BasePacket.cpp
6>c:\projects\seventhumbral\daemon\packets\basepacket.cpp(54): warning C4244: '=' : conversion de 'time_t' en 'uint32', perte possible de données
6>  Main.cpp
6>  Log.cpp
6>  LobbyServerPlayer.cpp
6>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
6>  LobbyServer.cpp
6>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
6>  Instance.cpp
6>c:\projects\seventhumbral\daemon\instance.cpp(42): warning C4244: 'initialisation' : conversion de 'double' en 'float', perte possible de données
6>  GlobalData.cpp
6>  GameServerPlayer.cpp
6>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
6>  GameServer.cpp
6>  DatabaseConnectionManager.cpp
6>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
6>  Clock.cpp
6>  Character.cpp
6>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
6>  AppearanceDatabase.cpp
6>  AppConfig.cpp
6>  PlayerActor.cpp
6>c:\projects\framework\include\mysql\mysqldefs.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'mysql.h' : No such file or directory
6>  EnemyActor.cpp
6>  Actor.cpp
6>  Génération de code en cours...
========== Génération : 6 a réussi, 1 a échoué, 7 mis à jour, 0 a été ignoré ==========

**Comment by jpd002** [comment]
I mean, quoting the path and keeping the spaces, like this: 
`"C:\Program Files\MySQL\MySQL Connector C 6.1"`.

**Comment by AlexandreCA** [comment]
@jpd002 Ok, I have a new error message during compilation.

11>------ Début de la génération : Projet : Workshop, Configuration : Debug Win32 ------
10>  Daemon.vcxproj -> C:\Projects\SeventhUmbral\build_win32\Win32\Debug\ffxivd.exe
10>  Le fichier spécifié est introuvable.
10>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: La commande "copy C:\Program Files\MySQL\MySQL Connector C 6.1\lib\libmysql.dll C:\Projects\SeventhUmbral\build_win32\Win32\Debug\
10>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" s'est arrêtée avec le code 1.
11>  Workshop.vcxproj -> C:\Projects\SeventhUmbral\build_win32\Win32\Debug\Workshop.exe
11>          1 fichier(s) copié(s).
========== Génération : 10 a réussi, 1 a échoué, 3 mis à jour, 0 a été ignoré ==========

sorry but my visual studio is in French. If you not understand, I can you translate it.

**Comment by jpd002** [comment]
Does `C:\Program Files\MySQL\MySQL Connector C 6.1\lib\libmysql.dll` exist?

**Comment by AlexandreCA** [comment]
@jpd002 Yes, he exist but I dont know where I have to retransmit this path.

![erreur](https://cloud.githubusercontent.com/assets/15184122/12061646/9ea06d90-af59-11e5-958b-ac15d619c474.png)

**Comment by jpd002** [comment]
Humm, could you try adding quotes to the source file path of the copy command in `GeneralSettings_Daemon.props` (https://github.com/jpd002/SeventhUmbral/blob/master/build_win32/GeneralSettings_Daemon.props#L15)? 

Something like that: `copy "$(MYSQL_PATH)\lib\libmysql.dll" $(OutputPath)`

**Comment by AlexandreCA** [comment]
@jpd002 Good game! Its works . Now I have one last question, in the tutorial which is on github , you talk about creating a given base. But how do you do? I use Navicat for my basic view has given SQL to another server .

**Comment by Caladius** [comment]
@jpd002 Quick Question: i have eliminated much of build errors now. the only one remaining is the "zlib-1.2.8 (load failed)" issue. when trying to reload the project i receive an error:

The project file
'H:Download\Server\Dependencies\build_win32\zlib-1.2.8.vcxproj'
has been moved, renamed or is not on your computer.

i redownloaded and checked the master files and could not find any instance of that file. I have zlib-1.2.8 in my dependencies folder but theres no vcxproj file included either.

Any idea? hopefuly its something stupid.

**Comment by jpd002** [comment]
Humm, the file should be there: https://github.com/jpd002/Play-Dependencies/tree/master/build_win32. Maybe your branch is still out of date?

**Comment by Caladius** [comment]
It may have been possible. redownloading the files from the link you provided resolved that. the last error i am facing is:

LNK1104 - cannot open file 'libbost_filesystem-vc140-mt-gd-1_60.lib

upon searching the NuGet Packages folder that was created upon my build attempts i noticed version 1.59 was downloaded. I downloaded Boost 1.60 to attempt to resolve but it does not contain the libboost file needed. (hopefully this is the last piece of help ill need. I am so close to the end)

Thank you for your patience and extreme knowledge input with this rather lengthy issue.

**Comment by jpd002** [comment]
That's actually my bad. I've updated the project files to download the proper NuGet packages. It should work if you update your branch.

**Comment by Caladius** [comment]
Thanks for the update, that resolved the boost issues but opened some other errors. I included them below in a screenshot.

![build errors](https://cloud.githubusercontent.com/assets/8377717/12870805/792ee860-cd23-11e5-8642-996b08ca71df.png)

**Comment by Caladius** [comment]
@jpd002 Upon some deeper investigation with a friend of mine we are unsure of what result the "operator" is trying to receive. (we think it may be receiving a response that it does not like)

@jpd002 and @AlexandreCA 
Below is where we traced the issue to, do either of you know what this means?:

![operator build errors](https://cloud.githubusercontent.com/assets/8377717/12900187/0ebf0a94-ce83-11e5-81e8-77c22499187d.png)

Thanks!

**Comment by Caladius** [comment]
Hey,
 Closing this out. I figured out what triggered the issue. Thanks again, the server now runs perfectly!  Great job with it so far.

**Comment by jpd002** [comment]
Awesome, glad you got it to work! Even though I haven't done any change to the server in a while, I'm still open to PRs and suggestions.

**Comment by Caladius** [comment]
Thats my plan! Once I get in there and figure out what I'm doing I want to be able to submit updates to help you out as well.
